# Site settings
title: Freshman
tagline: Freshman like Fish
author: Lijia YU
email: yu@lijiayu.net
  # this means to ignore newlines until "baseurl:"
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
description: "Freshman is a jekyll blog theme"
keywords: "Jekyll, Freshman, theme"
baseurl: "/freshman" # the subpath of your site, e.g. /blog/
url: "http://yulijia.net/freshman" # the base hostname & protocol for your site
twitter_username: yulijia
github_username:  yulijia
disqus_shortname: freshmantheme
favicon:     "images/favicon.ico"
#touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-57979084-1 # put YOUR key here to enable tracking! (blank to disable)

aboutme: Hi, this is Lijia Yu. I am a scientist.
aboutme_photo: https://i.imgur.com/15BT1.jpg



default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Resent_Posts: "Resent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "//"
      Taggedwith: "//"
      PostDate: "// "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Resent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


Blogroll:
    - name: Freshman21
      href: http://yulijia.net/freshman21
      title: Another Jekyll blog theme
    - name: author's website
      href: http://yulijia.net/
      title: Lijia Yu's website

# Build setting
markdown: kramdown
highlighter: pygments
paginate: 5
